/**
 * HLS - Tests
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-06-20T13:31:11Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Test'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Test'));
  } else {
    // Browser globals (root is window)
    if (!root.HlsTests) {
      root.HlsTests = {};
    }
    root.HlsTests.Tests = factory(root.HlsTests.ApiClient, root.HlsTests.Test);
  }
}(this, function(ApiClient, Test) {
  'use strict';




  /**
   * The Tests model module.
   * @module model/Tests
   * @version 2017-06-20T13:31:11Z
   */

  /**
   * Constructs a new <code>Tests</code>.
   * @alias module:model/Tests
   * @class
   * @extends Array
   */
  var exports = function() {
    var _this = this;
    _this = new Array();
    Object.setPrototypeOf(_this, exports);

    return _this;
  };

  /**
   * Constructs a <code>Tests</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Tests} obj Optional instance to populate.
   * @return {module:model/Tests} The populated <code>Tests</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'Test');

    }
    return obj;
  }




  return exports;
}));


