/**
 * HLS - Tests
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-06-20T13:31:11Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Empty', 'model/Test', 'model/TestMarkers', 'model/Tests', 'api/DefaultApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Empty'), require('./model/Test'), require('./model/TestMarkers'), require('./model/Tests'), require('./api/DefaultApi'));
  }
}(function(ApiClient, Empty, Test, TestMarkers, Tests, DefaultApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var HlsTests = require('index'); // See note below*.
   * var xxxSvc = new HlsTests.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new HlsTests.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new HlsTests.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new HlsTests.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 2017-06-20T13:31:11Z
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Empty model constructor.
     * @property {module:model/Empty}
     */
    Empty: Empty,
    /**
     * The Test model constructor.
     * @property {module:model/Test}
     */
    Test: Test,
    /**
     * The TestMarkers model constructor.
     * @property {module:model/TestMarkers}
     */
    TestMarkers: TestMarkers,
    /**
     * The Tests model constructor.
     * @property {module:model/Tests}
     */
    Tests: Tests,
    /**
     * The DefaultApi service constructor.
     * @property {module:api/DefaultApi}
     */
    DefaultApi: DefaultApi
  };

  return exports;
}));
