/**
 * HLS - Tests
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-06-20T13:31:11Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HlsTests);
  }
}(this, function(expect, HlsTests) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HlsTests.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('testDelete', function() {
      it('should call testDelete successfully', function(done) {
        //uncomment below and update the code to test testDelete
        //instance.testDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('testGet', function() {
      it('should call testGet successfully', function(done) {
        //uncomment below and update the code to test testGet
        //instance.testGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('testOptions', function() {
      it('should call testOptions successfully', function(done) {
        //uncomment below and update the code to test testOptions
        //instance.testOptions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('testPut', function() {
      it('should call testPut successfully', function(done) {
        //uncomment below and update the code to test testPut
        //instance.testPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('testsGet', function() {
      it('should call testsGet successfully', function(done) {
        //uncomment below and update the code to test testsGet
        //instance.testsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('testsOptions', function() {
      it('should call testsOptions successfully', function(done) {
        //uncomment below and update the code to test testsOptions
        //instance.testsOptions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
